import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "@/components/Navbar";
import { Stack } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <Providers>
          <Stack spacing={0} direction={"column"} maxW={"100vw"} minH={"100vh"}>
            <Navbar />
            {children}
          </Stack>
        </Providers>
      </body>
    </html>
  );
}
